### ISSUE TITLE
Feature request: Bounce option for Sparkle effect

### ISSUE THREAD

**Issue by MathiasSeifert** [TheRealKasumi/TesLight#106]
The 'Sparkle'-effect should have an option (e.g. 'Bounce') that cases the sparkles to bounce back at the end of the LED strip and reverse direction instead of disappearing.
The spawning of new sparkles needs to take this into account as sparks could live forever with this option enabled and sparkle fade/sparkle friction set to 0.

**Comment by TheRealKasumi** [comment]
I will add a simple flag that will bounce the particles at the end of the strip when its set. Since the number of particles is static and can be adjusted by the user, I dont see an issue with infinite lifetime. In fact this could be intended by the user. So maybe you want 3 particles bouncing all the time. Imo this should be the decision of the user.
